---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    {{- include "modern-gitops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  instances: 1
  db:
    vendor: postgres
    host: {{ .Values.keycloak.database.host }}
    usernameSecret:
      name: postgresql-secrets
      key: username
    passwordSecret:
      name: postgresql-secrets
      key: password
  hostname:
    hostname: {{ .Values.keycloak.ingress.host | quote }}
  http:
    httpEnabled: false
    httpsPort: 8443
    tlsSecret: keycloak-tls-secret
  ingress:
    enabled: false
  proxy:
    headers: xforwarded
  serviceMonitor:
    enabled: {{ .Values.keycloak.serviceMonitor.enabled | default false }}
    interval: 10s
    scrapeTimeout: 5s
  additionalOptions:
    - name: proxy
      value: reencrypt