{{- if index .Values "keycloak" "database" "create" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres-db
  labels:
    {{- include "modern-gitops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  selector:
    matchLabels:
      app: keycloak-postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-postgres-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:13-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: password
        - name: PGDATA
          value: /data/pgdata
        - name: POSTGRES_DB
          value: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-db
  labels:
    {{- include "modern-gitops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  selector:
    app: keycloak-postgres-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    {{- include "modern-gitops-stack-module-keycloak.labels" $ | indent 4 }}
type: Opaque
data:
  username: {{ .Values.keycloak.database.username }}
  password: {{ .Values.keycloak.database.password }}